# Generated by Django 5.1.1 on 2024-10-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_team_designation_arabic_team_first_name_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='first_name_arabic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
