# Generated by Django 5.1.1 on 2024-10-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_team_first_name_arabic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='designation_arabic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name_arabic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
