# Generated by Django 5.1.1 on 2024-10-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_team_designation_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='designation_arabic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name_arabic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name_arabic',
            field=models.CharField(max_length=100),
        ),
    ]
